// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FASTBuildMonitorVSIX.Manifests
{
    internal sealed partial class Vsix
    {
        public const string Id = "FASTBuildMonitorVSIX.2b5eff03-aa25-48ab-b76b-d380c3ff6d6c";
        public const string Name = "FASTBuildMonitorVSIX";
        public const string Description = @"FASTBuild Visual Studio viewer.
Vs 2022";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Ubisoft_KnownShippable";
        public const string Tags = "";
    }
}
