// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FASTBuildMonitorVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFASTBuildMonitorPackageString = "73de7c44-188b-45d3-aab2-19af8724c5c9";
        public static Guid guidFASTBuildMonitorPackage = new Guid(guidFASTBuildMonitorPackageString);

        public const string guidFASTBuildMonitorPackageCmdSetString = "f5f8a562-4be2-48ed-93d7-dc122dd25775";
        public static Guid guidFASTBuildMonitorPackageCmdSet = new Guid(guidFASTBuildMonitorPackageCmdSetString);

        public const string guidImagesString = "e6461ab7-05a5-42cf-b1fb-08c8e0783ddf";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FASTBuildMonitorCommandId = 0x0100;
        public const int FASTBuildMonitorToolsCommandId = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}