// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FASTBuildMonitorVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "FASTBuildMonitorVSIX.44bf85a5-7635-4a2e-86d7-7b7f3bf757a8";
        public const string Name = "FASTBuildMonitorVSIX";
        public const string Description = @"FASTBuild Visual Studio viewer.";
        public const string Language = "en-US";
        public const string Version = "1.101";
        public const string Author = "Ubisoft_KnownShippable";
        public const string Tags = "";
    }
}
